### ISSUE TITLE
keyword可以自行设置吗?

### ISSUE THREAD

**Issue by wedo99** [vimhandbook/vimhandbook.github.io#2]
Abbreviations 简码输入完之后我希望它只是补全一下而不是输入空格或者其他任何字符,比如说我希望按一下Leader键或者<C-f>键自动补全,这个可以实现吗?应该怎么设置呢?

**Comment by wxnacy** [comment]
> Abbreviations 简码输入完之后我希望它只是补全一下而不是输入空格或者其他任何字符,比如说我希望按一下Leader键或者键自动补全,这个可以实现吗?应该怎么设置呢?

你好  Abbreviations 的功能就是快速输入，输入空格或者 `@,48-57,_,192-255` 中的任意字符是为了激活它，自动补全需要其他特性来实现，关于自动补全我推荐 youcompleteme  是目前最强大的自动补全的插件，可以看这篇文章安装 https://wxnacy.com/2017/09/22/vim-plugin-youcompleteme/
